module.exports.Company = require('./company.model')
module.exports.Location = require('./location.model')
module.exports.Region = require('./region.model')
module.exports.Department =  require('./department.model')
module.exports.UserType = require('./userType.model')
module.exports.LeavePolicy = require('./leavePolicy.model')
module.exports.ShiftTime = require('./shiftTime.model')