module.exports = {
    REGION: {
        NAME_EXISTS: "Name already exists",
        CODE_EXISTS: "Code already exists",
        NOT_FOUND: "Region not found",
        CREATE_SUCCESS: "Region Created Successfully",
        UPDATE_SUCCESS: "Region Updated Successfully",
        DELETE_SUCCESS: "Region Deleted Successfully",
    },
    LOCATION: {
        NAME_EXISTS: "Name already exists",
        NOT_FOUND: "Location not found",
        CREATE_SUCCESS: "Location Created Successfully",
        UPDATE_SUCCESS: "Location Updated Successfully",
        DELETE_SUCCESS: "Location Deleted Successfully",
    },
    COMPANY:{
        NAME_EXISTS: "Name already exists",
        CODE_EXISTS: "Code already exists",
        NOT_FOUND: "Company not found",
        CREATE_SUCCESS: "Company Created Successfully",
        UPDATE_SUCCESS: "Company Updated Successfully",
        DELETE_SUCCESS: "Company Deleted Successfully",
    },
    DEPARTMENT: {
        NAME_EXISTS: "Name already exists for selected Company",
        NOT_FOUND: "Department not found",
        CREATE_SUCCESS: "Department Created Successfully",
        UPDATE_SUCCESS: "Department Updated Successfully",
        DELETE_SUCCESS: "Department Deleted Successfully",
    },
    USER_TYPE: {
        TYPE_EXISTS: "User Type already exists",
        NOT_FOUND: "User Type not found",
        CREATE_SUCCESS: "User Type Created Successfully",
        UPDATE_SUCCESS: "User Type Updated Successfully",
        DELETE_SUCCESS: "User Type Deleted Successfully",
    },
    LEAVE_POLICY: {
        NAME_EXISTS: "Name already exists for selected Company",
        NOT_FOUND: "Leave Policy not found",
        CREATE_SUCCESS: "Leave Policy Created Successfully",
        UPDATE_SUCCESS: "Leave Policy Updated Successfully",
        DELETE_SUCCESS: "Leave Policy Deleted Successfully",
    },
    SHIFT_TIME: {
        NAME_EXISTS: "Name already exists for selected Company",
        NOT_FOUND: "Shift Time not found",
        CREATE_SUCCESS: "Shift Time Created Successfully",
        UPDATE_SUCCESS: "Shift Time Updated Successfully",
        DELETE_SUCCESS: "Shift Time Deleted Successfully",
    },
    LEAVE_POLICY_DETAIL: {
        ACTIVE_EXISTS: "Active Leave details already exists for selected Leave Policy",
        NOT_FOUND: "Leave Policy Detail not found",
        CREATE_SUCCESS: "Leave Policy Detail Created Successfully",
        UPDATE_SUCCESS: "Leave Policy Detail Updated Successfully",
        DELETE_SUCCESS: "Leave Policy Detail Deleted Successfully",
    }
}